import React, { useState, useMemo } from 'react';

export default function SummaryReport({ objects, onReset, onBackToWorkspace }) {
  const [activeTab, setActiveTab] = useState('metrics');
  const [allowExportAnyway, setAllowExportAnyway] = useState(false);
  
  const pendingCount = useMemo(() => {
    return objects.filter(o => o.translation.requiresAi).length;
  }, [objects]);

  // Order of categories for final assembly
  const categoryOrder = ['SCHEMA', 'EXTENSION', 'ENUM', 'DOMAIN', 'COMPOSITE', 'SEQUENCE', 'TABLE', 'CONSTRAINT', 'INDEX', 'VIEW', 'FUNCTION', 'PROCEDURE', 'TRIGGER', 'DATA', 'OTHER'];

  // Aggregate metrics and organize code
  const reportData = useMemo(() => {
    const stats = {
      total: objects.length,
      SCHEMA: 0,
      EXTENSION: 0,
      ENUM: 0,
      DOMAIN: 0,
      COMPOSITE: 0,
      SEQUENCE: 0,
      TABLE: 0,
      INDEX: 0,
      CONSTRAINT: 0,
      complex: 0, // VIEWS, FUNCTIONS, PROCEDURES, TRIGGERS
      warnings: 0
    };

    const warningsList = [];
    const orderedScripts = [];

    // Group objects by type
    const grouped = {};
    categoryOrder.forEach(type => {
      grouped[type] = [];
    });

    objects.forEach(obj => {
      // Update stats
      if (stats[obj.classified.type] !== undefined) {
        stats[obj.classified.type]++;
      }
      if (['VIEW', 'FUNCTION', 'PROCEDURE', 'TRIGGER'].includes(obj.classified.type)) {
        stats.complex++;
      }

      // Track warnings
      if (obj.translation.warnings && obj.translation.warnings.length > 0) {
        stats.warnings += obj.translation.warnings.length;
        obj.translation.warnings.forEach(warn => {
          warningsList.push({
            type: obj.classified.type,
            name: `${obj.classified.schema}.${obj.classified.name}`,
            text: warn
          });
        });
      }

      // Add to group
      if (grouped[obj.classified.type]) {
        grouped[obj.classified.type].push(obj);
      } else {
        grouped['OTHER'].push(obj);
      }
    });

    // Assemble ordered SQL
    categoryOrder.forEach(type => {
      const list = grouped[type];
      if (list && list.length > 0) {
        orderedScripts.push(`\n-- =========================================================\n-- TYPE: ${type}\n-- =========================================================\n`);
        list.forEach(obj => {
          orderedScripts.push(`-- Object: [${obj.classified.type}] ${obj.classified.schema}.${obj.classified.name}`);
          orderedScripts.push(obj.translation.tsql);
          orderedScripts.push(''); // spacing
        });
      }
    });

    const combinedSql = orderedScripts.join('\n');

    return {
      stats,
      warningsList,
      combinedSql
    };
  }, [objects]);

  const downloadSqlFile = () => {
    const blob = new Blob([reportData.combinedSql], { type: 'text/sql' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'converted_sql_server_schema.sql';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadReportFile = () => {
    const mdReport = `# Database Schema Conversion Report
Generated by TranspileDB on ${new Date().toLocaleDateString()}

## 1. Summary Metrics
- **Total PostgreSQL Objects Parsed**: ${reportData.stats.total}
- **Schemas**: ${reportData.stats.SCHEMA}
- **Extensions**: ${reportData.stats.EXTENSION}
- **Composite Types**: ${reportData.stats.COMPOSITE}
- **Sequences**: ${reportData.stats.SEQUENCE}
- **Tables**: ${reportData.stats.TABLE}
- **Indexes**: ${reportData.stats.INDEX}
- **Alter Table Constraints**: ${reportData.stats.CONSTRAINT}
- **PL/pgSQL Logic Objects**: ${reportData.stats.complex}
- **Total Warnings Flagged**: ${reportData.stats.warnings}

## 2. Items Requiring Manual Review (${reportData.warningsList.length})
${reportData.warningsList.length === 0 ? '_No warnings or manual actions required!_' : reportData.warningsList.map((w, i) => `${i + 1}. **[${w.type}] ${w.name}**: ${w.text}`).join('\n')}

---
_Note: Double check all functions and trigger behaviors before deploying to production. PL/pgSQL to T-SQL transitions might require structural adjustments for cursor logic and set-based actions._
`;
    const blob = new Blob([mdReport], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'schema_conversion_report.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copySqlToClipboard = () => {
    navigator.clipboard.writeText(reportData.combinedSql);
    alert('Full T-SQL script copied to clipboard!');
  };

  return (
    <div className="summary-container container">
      <div className="summary-nav-header">
        <button className="btn btn-secondary" onClick={onBackToWorkspace} style={{ display: 'inline-flex', alignItems: 'center' }}>
          <svg viewBox="0 0 24 24" width="16" height="16" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: '0.5rem' }}>
            <polyline points="15 18 9 12 15 6" />
          </svg>
          Back to Editor
        </button>
        <h2>Conversion Summary & Review</h2>
      </div>

      {/* Metric Cards */}
      <div className="summary-grid">
        <div className="metric-card glass-panel border-glow">
          <span className="metric-label">Objects Converted</span>
          <span className="metric-value">{reportData.stats.total}</span>
        </div>
        <div className="metric-card glass-panel">
          <span className="metric-label">Tables & Constraints</span>
          <span className="metric-value">{reportData.stats.TABLE + reportData.stats.CONSTRAINT}</span>
        </div>
        <div className="metric-card glass-panel">
          <span className="metric-label">AI Logic Objects</span>
          <span className="metric-value">{reportData.stats.complex}</span>
        </div>
        <div className="metric-card glass-panel highlight-warn">
          <span className="metric-label">Warnings Flagged</span>
          <span className="metric-value">{reportData.stats.warnings}</span>
        </div>
      </div>

      {/* Block/Warning banner if pending translation objects exist */}
      {pendingCount > 0 && (
        <div className="banner-alert danger glass-panel border-glow" style={{ margin: '1rem 0 1.5rem 0', padding: '1.25rem', border: '1px solid var(--error-border)', background: 'var(--error-bg)', borderRadius: 'var(--radius-md)', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          <div className="banner-title" style={{ color: 'var(--error)', display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '1rem', fontWeight: '800' }}>
            <svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round">
              <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
              <line x1="12" y1="9" x2="12" y2="13" />
              <line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
            <span>Translation Incomplete: {pendingCount} Pending Objects</span>
          </div>
          <p style={{ fontSize: '0.88rem', color: 'var(--text-secondary)', lineHeight: '1.5', margin: 0 }}>
            There are still {pendingCount} database logic objects (views, functions, procedures, or triggers) waiting for AI translation. Exporting now will output a script with missing T-SQL logic.
          </p>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button className="btn btn-primary btn-sm" onClick={onBackToWorkspace} style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
              <svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" style={{ marginRight: '0.4rem' }}>
                <polyline points="15 18 9 12 15 6" />
              </svg>
              Go Back & Translate
            </button>
            {!allowExportAnyway ? (
              <button className="btn btn-secondary btn-sm" onClick={() => setAllowExportAnyway(true)} style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                Show Export Actions Anyway
              </button>
            ) : (
              <button className="btn btn-secondary btn-sm" onClick={() => setAllowExportAnyway(false)} style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                Keep Export Actions Blocked
              </button>
            )}
          </div>
        </div>
      )}

      {/* Main Panel */}
      <div className="summary-panel glass-panel">
        <div className="panel-tabs">
          <button 
            className={`tab-btn ${activeTab === 'metrics' ? 'active' : ''}`}
            onClick={() => setActiveTab('metrics')}
          >
            Review & Warnings
          </button>
          <button 
            className={`tab-btn ${activeTab === 'sql' ? 'active' : ''}`}
            onClick={() => setActiveTab('sql')}
          >
            Combined T-SQL Script
          </button>

          <div className="panel-tab-actions">
            <button className="btn btn-secondary btn-sm" onClick={downloadReportFile}>
              <svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
              Download Report
            </button>
            <button 
              className={`btn btn-primary btn-sm ${pendingCount > 0 && !allowExportAnyway ? 'disabled' : ''}`} 
              onClick={downloadSqlFile}
              disabled={pendingCount > 0 && !allowExportAnyway}
            >
              <svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download SQL Script
            </button>
          </div>
        </div>

        <div className="tab-content">
          {activeTab === 'metrics' ? (
            <div className="metrics-tab">
              {reportData.warningsList.length === 0 ? (
                <div className="success-banner">
                  <svg viewBox="0 0 24 24" width="32" height="32" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" className="success-icon">
                    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                    <polyline points="22 4 12 14.01 9 11.01" />
                  </svg>
                  <div>
                    <h3>Schema converted successfully with zero errors!</h3>
                    <p>All PostgreSQL objects were translated without warnings. Your schema is fully compatible with SQL Server syntax.</p>
                  </div>
                </div>
              ) : (
                <div className="warnings-section">
                  <div className="section-header">
                    <h3>Review Items ({reportData.warningsList.length})</h3>
                    <p>The following items contain features without a direct SQL Server equivalent or required conversion adjustments. We recommend examining these objects carefully.</p>
                  </div>
                  <div className="warnings-scroll-list">
                    {reportData.warningsList.map((warn, i) => (
                      <div key={i} className="warning-item glass-panel">
                        <div className="warn-meta">
                          <span className="badge badge-secondary">{warn.type}</span>
                          <strong className="warn-obj-name">{warn.name}</strong>
                        </div>
                        <p className="warn-text">{warn.text}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="sql-tab">
              <div className="sql-preview-header">
                <span>Ordered T-SQL Output Script</span>
                <button className="btn-action-copy" onClick={copySqlToClipboard}>
                  <svg viewBox="0 0 24 24" width="15" height="15" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                  </svg>
                  Copy T-SQL Code
                </button>
              </div>
              <div className="sql-preview-box">
                <pre><code>{reportData.combinedSql}</code></pre>
              </div>
            </div>
          )}
        </div>
      </div>

      <style>{`
        .summary-container {
          padding-top: 2rem;
          padding-bottom: 4rem;
          display: flex;
          flex-direction: column;
          gap: 2rem;
          animation: fadeIn 0.4s ease-out;
        }
        
        .summary-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 1.25rem;
        }
        
        @media (max-width: 768px) {
          .summary-grid {
            grid-template-columns: 1fr 1fr;
          }
        }
        
        .metric-card {
          padding: 1.5rem;
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
          background: var(--panel-bg);
          border: 1px solid var(--panel-border);
          border-radius: var(--radius-md);
        }
        
        .metric-label {
          font-size: 0.85rem;
          color: var(--text-secondary);
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }
        
        .metric-value {
          font-size: 2.25rem;
          font-weight: 800;
          color: var(--text-primary);
          line-height: 1.1;
        }
        
        .border-glow {
          position: relative;
          box-shadow: var(--shadow-glow);
          border-color: rgba(99, 102, 241, 0.25);
        }
        
        .highlight-warn .metric-value {
          color: var(--warning);
        }
        
        .summary-panel {
          background: var(--panel-bg);
          border: 1px solid var(--panel-border);
          border-radius: var(--radius-lg);
          display: flex;
          flex-direction: column;
          min-height: 500px;
        }
        
        .panel-tabs {
          display: flex;
          align-items: center;
          border-bottom: 1px solid var(--panel-border);
          padding: 0 1.25rem;
          background: var(--panel-tab-bg, rgba(15, 23, 42, 0.3));
          border-radius: var(--radius-lg) var(--radius-lg) 0 0;
          flex-wrap: wrap;
        }
        
        .tab-btn {
          background: none;
          border: none;
          color: var(--text-secondary);
          font-family: var(--font-sans);
          font-weight: 600;
          font-size: 0.95rem;
          padding: 1.25rem 1.5rem;
          cursor: pointer;
          position: relative;
          transition: color 0.2s;
        }
        
        .tab-btn:hover {
          color: var(--text-primary);
        }
        
        .tab-btn.active {
          color: var(--primary);
        }
        
        .tab-btn.active::after {
          content: '';
          position: absolute;
          bottom: -1px;
          left: 0;
          right: 0;
          height: 2px;
          background: var(--primary);
          box-shadow: 0 0 8px var(--primary);
        }
        
        .panel-tab-actions {
          margin-left: auto;
          display: flex;
          align-items: center;
          gap: 0.75rem;
          padding: 0.75rem 0;
        }
        
        @media (max-width: 640px) {
          .panel-tab-actions {
            margin-left: 0;
            width: 100%;
            padding-bottom: 1rem;
          }
        }
        
        .btn-sm {
          padding: 0.45rem 1rem;
          font-size: 0.85rem;
          height: 34px;
        }
        
        .tab-content {
          padding: 1.75rem;
          flex: 1;
          display: flex;
          flex-direction: column;
        }
        
        .success-banner {
          background: var(--success-bg);
          border: 1px solid var(--success-border);
          border-radius: var(--radius-md);
          padding: 2rem;
          display: flex;
          gap: 1.5rem;
          align-items: flex-start;
          animation: fadeIn 0.3s ease-out;
        }
        
        .success-icon {
          color: var(--success);
          flex-shrink: 0;
        }
        
        .success-banner h3 {
          font-size: 1.2rem;
          font-weight: 700;
          color: var(--text-primary);
          margin-bottom: 0.5rem;
        }
        
        .success-banner p {
          color: var(--text-secondary);
          line-height: 1.6;
          font-size: 0.95rem;
        }
        
        .warnings-section {
          display: flex;
          flex-direction: column;
          gap: 1.25rem;
          animation: fadeIn 0.3s ease-out;
        }
        
        .section-header h3 {
          font-size: 1.15rem;
          font-weight: 700;
          color: var(--text-primary);
          margin-bottom: 0.25rem;
        }
        
        .section-header p {
          font-size: 0.85rem;
          color: var(--text-secondary);
        }
        
        .warnings-scroll-list {
          display: flex;
          flex-direction: column;
          gap: 0.75rem;
          max-height: 420px;
          overflow-y: auto;
          padding-right: 0.5rem;
        }
        
        .warning-item {
          padding: 1rem 1.25rem;
          background: var(--warning-bg);
          border: 1px solid var(--warning-border);
          border-radius: var(--radius-sm);
        }
        
        .warning-item:hover {
          border-color: var(--warning-border);
        }
        
        .warn-meta {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 0.4rem;
        }
        
        .warn-obj-name {
          font-size: 0.9rem;
          color: var(--text-primary);
        }
        
        .warn-text {
          font-size: 0.82rem;
          color: var(--text-secondary);
          line-height: 1.45;
        }
        
        .sql-tab {
          display: flex;
          flex-direction: column;
          gap: 1rem;
          flex: 1;
        }
        
        .sql-preview-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 0.85rem;
          color: var(--text-secondary);
        }
        
        .btn-action-copy {
          background: none;
          border: none;
          color: var(--primary);
          cursor: pointer;
          font-family: var(--font-sans);
          font-weight: 600;
          display: flex;
          align-items: center;
          gap: 0.4rem;
          font-size: 0.85rem;
          transition: color 0.2s;
        }
        
        .btn-action-copy:hover {
          color: var(--primary-hover);
        }
        
        .sql-preview-box {
          background: var(--code-bg, rgba(8, 12, 24, 0.55));
          border: 1px solid var(--panel-border);
          border-radius: var(--radius-sm);
          padding: 1.25rem;
          font-family: var(--font-mono);
          font-size: 0.85rem;
          line-height: 1.5;
          max-height: 500px;
          overflow: auto;
          white-space: pre;
          color: var(--code-text, #cbd5e1);
        }
        
        .sql-preview-box code {
          background: none;
          padding: 0;
          color: var(--code-text, #cbd5e1);
        }
      `}</style>
    </div>
  );
}
